export interface ClientData {
  cliente_nome?: string,
  cliente_cpf?: string,
  cliente_email?: string,
  cliente_telefone?: string,
  cliente_cidade?: string,
  numero_processo?: string,
  tribunal?: string,
  vara?: string,
  area_atuacao?: string,
  data_distribuicao?: string,
  status_processo?: string,
  estagio_atual?: string,
  desfecho?: string,
  data_desfecho?: string,
  valor_causa?: string,
  valor_honorario?: string,
  valor_cliente?: string,
}